"""Builds the extraction inventory: every section, figure, table, and
detected business-rule identifier found for a version, plus any warnings
raised along the way (Phase 3 item 9-10 of the reference-module plan)."""

import re
from dataclasses import dataclass, field

from .toc import FigureOrTableEntry, SectionEntry

# CDSi business rule IDs look like "CALCDTAGE-1", "FORECASTDT-2",
# "CONDSKIP-3" - an all-caps mnemonic, a hyphen, and a number. Word-boundary
# anchored so we don't match inside an unrelated all-caps run.
_BUSINESS_RULE_RE = re.compile(r"\b([A-Z]{4,}(?:[A-Z0-9]*)-\d+)\b")


@dataclass
class SectionIndexEntry:
    number: str
    title: str
    filename: str
    warnings: list[str] = field(default_factory=list)
    business_rules: list[str] = field(default_factory=list)


@dataclass
class ExtractionIndex:
    version: str
    sections: list[SectionIndexEntry]
    figures: list[FigureOrTableEntry]
    tables: list[FigureOrTableEntry]
    table_warnings: dict[str, list[str]]
    figure_warnings: dict[str, list[str]]

    def all_warnings(self) -> list[str]:
        warnings = []
        for s in self.sections:
            warnings.extend(f"section {s.number}: {w}" for w in s.warnings)
        for number, ws in self.table_warnings.items():
            warnings.extend(f"table {number}: {w}" for w in ws)
        for number, ws in self.figure_warnings.items():
            warnings.extend(f"figure {number}: {w}" for w in ws)
        return warnings


def find_business_rules(text: str) -> list[str]:
    seen: list[str] = []
    for match in _BUSINESS_RULE_RE.finditer(text):
        rule_id = match.group(1)
        if rule_id not in seen:
            seen.append(rule_id)
    return seen


def render_index_markdown(index: ExtractionIndex) -> str:
    lines = [f"# Extraction Index - Logic Specification v{index.version}", ""]
    lines.append(
        "Generated by `cdsi_reference_tools logic-spec extract`. This file is "
        "fully regenerable; do not hand-edit it."
    )
    lines.append("")
    lines.append("## Sections")
    lines.append("")
    lines.append("| Number | Title | Business Rules | Warnings |")
    lines.append("| --- | --- | --- | --- |")
    for s in index.sections:
        rules = ", ".join(s.business_rules) if s.business_rules else "-"
        warn = f"{len(s.warnings)}" if s.warnings else "-"
        lines.append(f"| {s.number} | {s.title} | {rules} | {warn} |")

    lines.append("")
    lines.append("## Tables")
    lines.append("")
    lines.append("| Number | Title | Page | Status |")
    lines.append("| --- | --- | --- | --- |")
    for t in index.tables:
        status = "ok" if not index.table_warnings.get(t.number) else "needs review (see warnings)"
        lines.append(f"| {t.number} | {t.title} | {t.page} | {status} |")

    lines.append("")
    lines.append("## Figures")
    lines.append("")
    lines.append("| Number | Title | Page | Status |")
    lines.append("| --- | --- | --- | --- |")
    for f in index.figures:
        status = "ok" if not index.figure_warnings.get(f.number) else "needs review (see warnings)"
        lines.append(f"| {f.number} | {f.title} | {f.page} | {status} |")

    warnings = index.all_warnings()
    lines.append("")
    lines.append(f"## Warnings ({len(warnings)})")
    lines.append("")
    if warnings:
        for w in warnings:
            lines.append(f"- {w}")
    else:
        lines.append("None.")
    lines.append("")
    return "\n".join(lines)
